mysite/myapp/urls.py
from django.urls import path
from . import views
app_name = 'myapp'
urlpatterns = [
    path("", views.index, name='home'),
    path("details/<int:my_id>", views.index_item, name='item'),           #не сделано
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('myapp.urls')),
    path("details/", include('myapp.urls', namespace='myapp')),
]

mysite/myapp/models.py
from django.db import models


class Product(models.Model):
    name = models.CharField(max_length=100)
    price = models.IntegerField()
    description = models.CharField(max_length=200)

    def __str__(self):
        return self.name

mysite/myapp/views.py
from django.shortcuts import render
from .models import Product


def index(request):
    items = Product.objects.all()
    return render(request, 'myapp/index.html', {'items': items})


def index_item(request, my_id):
    item = Product.objects.get(id=my_id)
    data = {
        'item': item,
    }
    return render(request, 'myapp/details.html', data)

mysite/myapp/templates/myapp/details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>dvmf</title>
</head>
<body>
    {{ item.name }}
</body>
</html>

mysite/myapp/templates/myapp/index.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'myapp/style.css' %}">
    <title>Главная страница</title>
</head>
<body>
    {% for el in items %}
    <a href="{% url 'myapp:item' el.id %}">
        <h1>{{ el.id }}</h1>
    </a>
        <h1>{{ el.name }}</h1>
        <h1>{{ el.price }}</h1>
        <h1>{{ el.description }}</h1>
    {% endfor %}
</body>
</html>